train:
  epochs: 300
  accelerator: gpu
  number_of_checkpoints: 3
  devices: 1
  patience: 50
  run_name: test0
  experiment_name: crabnet_basic
  version: '1.0'

data:
  # general data specs
  root_dir: data/cgcnn_data_mp_metal_nonmetal    # cgcnn_data_mp_metal_nonmetal    #cgcnn_junwen_july_3_kdis
  id_prop_csv: id_prop.csv
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  train_path: crabnet_data/train.csv
  val_path: crabnet_data/val.csv
  test_path: crabnet_data/test.csv
  random_seed: 177
  batch_size: 1024
  scale: false
  stratify: false
  pin_memory: false
  n_elements: infer
  scale_y: false
  atomic_features:
    atom_feature_strategy:
      atom_feature_file: embeddings/atom_init_with_sssp_cutoffs.json # cgcnn_original
      soap_atomic: false
    soap_params: 
      r_cut: 10.0
      n_max: 8
      l_max: 6
      sigma: 1.0

model:  #clarify the question of weight initialization in lightning and random_seed for that
  name: crabnet
  out_dims: 3
  d_model: 512
  NN: 5
  heads: 4
  fudge: 0
  random_seed: 177
  classification: true
  robust_regression: false
  quantile_regression: false
  num_quantiles: 1 # 1 for QuantileLoss, 2 for IntervalScoreLoss
  num_classes: 2

loss:
  name: RobustL1Loss # RobustL2Loss, RobustL1Loss, QuantileLoss, CrossEntropyLoss, HuberLoss, L1Loss, MSELoss, StudentTLoss, IntervalScoreLoss
  quantile: 0.9 # for quantile regression
  student_nu: 5

optim:
  base_lr: 0.001
  max_lr: 0.005
  weights: false
  schedule: CyclicLR
  swa: false
  swa_lr: 0.0025
  swa_start: 0.3

prediction:
  predict_for_validation: true